Call `synchronize` on `@mutex`.
Changed in Rails 7.2. Was getting this error:

```
undefined method 'synchronize' for an instance of ActionController::ParamsWrapper::Options
```

I looked at the Rails source of this class this is overriding and found that `@mutex` was being set in the `initialize` method so we can make use of that.

https://github.com/rails/rails/blob/v7.2.0/actionpack/lib/action_controller/metal/params_wrapper.rb